language: node_js

node_js:
- '6.3.1'

cache:
  directories:
    - ./public/
    - ./node_modules

branches:
  only:
  - develop

before_install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install

before_script:
- git config --global user.name 'Travis CI'
- git config --global user.email 'bot@travis-ci.org'
- sed -i'' "s~git@github.com:wololock/wololock.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/wololock/wololock.github.io.git~" _config.yml

script:
- hexo generate

deploy:
  skip_cleanup: true
  provider: script
  script: hexo deploy
  on:
    branch: develop