language: node_js
node_js:
  - '4'
branches:
  only:
    - develop
before_install:
  - npm install -g hexo
  - npm install
before_script:
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'bot@travis-ci.org'
  - sed -i'' "s~git@github.com:wololock/wololock.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/wololock/wololock.github.io.git~" _config.yml
install:
  - hexo generate
script:
  - hexo deploy --silent
env:
  global:
    - secure: 0iHpfRdyuPrGPD6SJYJ+36pxwRpqw2bKVTghDohNVxuRTHSPGNJajsOoOHADILG68q7K1JVq/w9/jIlw6ElrJROuHYKx2lmqGkMFXN1pFPpcWMbyR1jXFB9lyvadZHy2C1L/xfz1Dt2EwDeyBZXJCPNwK8NYfiD5z4Fy4UIyToaqzwoHwPy6mX+9hORR3f+nPjmdCSxMIZajr1gQ9x7bBOipX14fTyABWAA5J4hxIlFQdTp50BdD79hc00zicCbmKXiCLm6X80waj+G9ESG4DCF5Hwb6ike4OvT0lUMY8AhrII707iskjCnXtvKbmyE3K1zdoy61sL7g9SYKqULbqD2ucmGWDK7+KjzZf+Avd8piJ7u4CS94jKlZf5pHkleVpXiBLkLM5AyOSbUuqMktciF6VCfHQI5PHv9sbyVBt2zfn/zkZ8vfqW5T5quJ9XpbASvnUvfZIkJ/WQ782mgKAGIgz24OPQxFco4isGeQoXnAHdELI77h8Xy/A6xD0aJkSqgKJRl97LPdLxRbEMLuF+7tyYJIz/3ehrZm+3IcJx0/WvLk0bECVswmboKkJ99aPZhr1jDMkmDM89NS1Re54Tx50i7g4UJqZhni6R24rt3XkVDplLOOZLwvr9WAW8C5FNA8Uv3sULu5+F5sSbBFmNhlxY8sE2zlAyt+/TiQMjo=
