version: 2
jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
            npm install hexo --save
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate blog
          command: hexo generate
      - deploy:
          name: Deploy website
          command: |
            if [ "${CIRCLE_BRANCH}" == "circleci" ]; then
              git config --global user.name "Circle CI"
              git config --global user.email "bot@circleci.com"
              sed -i'' "s~git@github.com:wololock/wololock.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/wololock/wololock.github.io.git~" _config.yml
              sh deploy.sh
            fi
